export const SET_USERS = 'SET_USERS';
export const SET_USERS_ASYNC = 'SET_USERS_ASYNC';
export const SELECT_USER = 'SELECT_USER';
export const SET_USERS_PAGE = 'SELECT_USER';
export const SET_USERS_PER_PAGE = 'SET_USERS_PER_PAGE';
export const SET_USERS_TOTAL_COUNT = 'SET_USERS_TOTAL_COUNT';
export const SET_USERS_SORT = 'SET_USERS_SORT';