export const SET_DEVICES = 'SET_DEVICES';
export const SET_DEVICES_ASYNC = 'SET_DEVICES_ASYNC';
export const SET_DEVICES_FOR_GROUP = 'SET_DEVICES_FOR_GROUP';
export const SET_DEVICES_ASYNC_FOR_GROUP = 'SET_DEVICES_ASYNC_FOR_GROUP';