export const SET_DEVICES = 'SET_DEVICES';
export const SET_DEVICES_ASYNC = 'SET_DEVICES_ASYNC';
export const SET_DEVICES_FOR_GROUP = 'SET_DEVICES_FOR_GROUP';
export const SET_DEVICES_ASYNC_FOR_GROUP = 'SET_DEVICES_ASYNC_FOR_GROUP';
export const SELECT_DEVICE = 'SELECT_DEVICE';
export const UPDATE_DEVICES_TABLE_FOR_GROUP = 'UPDATE_DEVICES_TABLE_FOR_GROUP';