name: React CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Run the tests
        run: yarn test-coverage-all